FROM mariux/document-service:staging
# FROM python:3.11

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -yqq --no-install-recommends wkhtmltopdf

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["./startup_wrapper.sh"]
