FROM python:3.11

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -yqq --no-install-recommends \
    libssl-dev libreadline-dev libpcap-dev \
    openssl apt-utils procps gcc \
    wkhtmltopdf \
    vim 

RUN python -m pip install --upgrade pip && pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["./startup_wrapper.sh"]
